### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by Anachron** [andyjsmith/Vultr-Dynamic-DNS#1]
So it seems like it doesn't work anymore. 

When I edit the dns-entry with  let's say ` 88.55.44.55` and run `python3 ddns.py` I get:

```
 vultrddns » python3 ddns.py
IP has changed since last checking.
Old IP on Vultr: 88.55.44.55, current server IP: <MY_LOCAL_IP>
Changed home (<number>) to <MY_LOCAL_IP> in <DOMAIN>
```

However when I log into the account and check my dns-entries its still `88.55.44.55` (and pinging `home.<DOMAIN>` still returns `88.55.44.55`).

**Comment by andyjsmith** [comment]
If you still want to use this repository and are having issues, please let me know and I'll look into it. Hadn't been checking issues.

**Comment by Anachron** [comment]
Yes still have these issues I will try to dig deeper into it soon.

**Comment by Anachron** [comment]
I've actually replaced this with a 10 line shell script that updates all my records using CURL. 
Thanks though!
