### ISSUE TITLE
Add a new function that renew automatically the free domain on no-ip.com periodically

### ISSUE THREAD

**Issue by bphd** [andyjsmith/Vultr-Dynamic-DNS#14]

**Comment by andyjsmith** [comment]
I don't see any reason to integrate with No-IP considering this tool is a _direct alternative to it_. The whole point of this tool is that you don't need to use services like No-IP and can just use your custom domain name + Vultr DNS. If I'm misunderstanding your request then please elaborate and give more details.

**Comment by bphd** [comment]
Vultr seems to have the need to own a physical server that we operate 24 7 and who is whitelisted in every DNS and IS, which is... Difficult

**Comment by andyjsmith** [comment]
If you don't have a Vultr server, why are you using Vultr DNS? Just switch to Cloudflare DNS and there are plenty of existing DDNS tools. You really need to give me more details here cause I have no idea what you're trying to do.

**Comment by bphd** [comment]
Trying to avoid [that](https://www.noip.com/support/knowledgebase/confirm-my-hostname-free-account-support-question-day/)

CloudFlare DUC isn't integrated in my router. My router only takes no-ip and some other paid solutions

**Comment by andyjsmith** [comment]
There is zero intersection between what you're describing and what this tool does. This tool has nothing to do with No-IP, find a different tool or create your own.
