### ISSUE TITLE
Force usage of ipv4 or ipv6 source ip address

### ISSUE THREAD

**Issue by cool-mist** [andyjsmith/Vultr-Dynamic-DNS#6]
When accessing vultr apis, make it configurable to force the `requests` module to stick to either ipv4 or ipv6 based on what user might have configured in their account settings.

On my desktop running windows, the request uses ipv4 address. On my raspberry pi running debian buster, python3 decides to use ipv6 as the source ip address in the tcp packet it sends out to vultr servers, and the vultr api rejects the request as the ip is not allowed.

The following snippet works for me

```
import requests.packages.urllib3.util.connection as urllib3_cn

def allowed_gai_family():
    family = socket.AF_INET    # force IPv4
    return family
```

**Comment by andyjsmith** [comment]
I'm considering this a non-issue. You should enable IPv6 API access in your account API settings if your host uses IPv6 by default. I added instructions in the readme.
