### ISSUE TITLE
The stock address to get ip addresses has an expired certificate

### ISSUE THREAD

**Issue by cool-mist** [andyjsmith/Vultr-Dynamic-DNS#7]
[This line](https://github.com/andyjsmith/Vultr-Dynamic-DNS/blob/master/ddns.py#L19) has an expired certificate and so the script is broken.

I used https://ifconfig.me to unblock myself.

I would suggest vultr to host a ipaddress utility api so that your customers are not dependent on 3rd party servers working correctly,

**Comment by andyjsmith** [comment]
I am not affiliated with Vultr and have no way of getting them to host an IP address utility. I updated the IP address provider to a different service.
